### ISSUE TITLE
Wise county, VA is failing. Possibly because there's a hole in the geometry.

### ISSUE THREAD

**Issue by sikanrong** [olagbk/region-labels#3]
Wise county, VA is failing label generation. Gotta figure out why, though it's likely because the geometry is a doughnut-shape. There are many counties with 'holes' in them, where the holes are actually counties fully that are fully surrounded on all sides by a single other 'doughnut' county. 

![wise_county_va](https://user-images.githubusercontent.com/85241/30707175-ef025bda-9efa-11e7-9556-d0f940e58a35.png)

**Comment by sikanrong** [comment]
Error: Convex vertices must be given in conter-clockwise winding.
    at new Convex (/private/var/www/primary_colors/node_modules/p2/src/shapes/Convex.js:115:15)
    at /private/var/www/primary_colors/node_modules/region-labels/lib/index.js:367:25
    at arrayEach (/private/var/www/primary_colors/node_modules/region-labels/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/private/var/www/primary_colors/node_modules/region-labels/node_modules/lodash/lodash.js:9359:14)
    at calculateLetters (/private/var/www/primary_colors/node_modules/region-labels/lib/index.js:366:11)
    at new RegionLabel (/private/var/www/primary_colors/node_modules/region-labels/lib/index.js:756:9)
    at /private/var/www/primary_colors/gulp/labels.js:91:26
    at arrayEach (/private/var/www/primary_colors/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/private/var/www/primary_colors/node_modules/lodash/lodash.js:9289:14)
    at drawGrid (/private/var/www/primary_colors/gulp/labels.js:83:11)
    at /private/var/www/primary_colors/gulp/labels.js:70:17
    at _fulfilled (/private/var/www/primary_colors/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/private/var/www/primary_colors/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/private/var/www/primary_colors/node_modules/q/q.js:796:13)
    at /private/var/www/primary_colors/node_modules/q/q.js:604:44
    at runSingle (/private/var/www/primary_colors/node_modules/q/q.js:137:13)

**Comment by sikanrong** [comment]
It's possible that I'm getting the error because on the server, we're getting the data directly from the shapefile, and in the shapefile perhaps the 'holes' are clockwise to distinguish them as negative space. On the client I use qgis to export the county to GeoJSON, which might spit out counter-clockwise verts just because...

**Comment by sikanrong** [comment]
It _definitely_ is that there's a hole and probably that the coordinates of the hole are clockwise instead of CCW. If we're getting coordinates directly from a shapefile, this is going to be an issue. However first we need to make sure that layering bodies is going to work with the P2.js Raycaster [See: Issue 6](https://github.com/olagbk/region-labels/issues/6)

**Comment by sikanrong** [comment]
Another example: Roanoke county VA

![roanoke](https://user-images.githubusercontent.com/85241/30923667-cb9090e8-a3ac-11e7-9818-1ae5bbeda98e.png)

**Comment by sikanrong** [comment]
I've been able to confirm that indeed the 'holes' in a geometry are denoted by counter clockwise vertices, which is at the root of this problem we're having...

**Comment by sikanrong** [comment]
well this is useful, with roanoke county (the one pictured above) I get the same error about CCW vertices as I get on the server. Error comes from the line: 

`var shape = new p2.Convex({ vertices: vertices });`

So P2 is just naturally incompatible with geojson format, but all we really have to do is pass the 'holes' as extra shapes within the outer shape and then interpret the collisions accordingly.

**Comment by sikanrong** [comment]
So I've mostly added support for geometry with holes. Basically now that I've internally adopted the GeoJSON standard within the library, I can give the 'holes' the special attention they need within the code. Bearing that in mind, I've managed to avoid the exception being thrown when creating a P2js convex shape for raycasting by reversing the vertices in the 'hole' geometry. Similarly I've written my own pointInside function for detecting if a point lie within the shape (or not), but this one takes into account the holes. 

Anyway closing this issue for now, the rest of 'hole'-geometry compatibility will be handled with [Issue 6](https://github.com/olagbk/region-labels/issues/6) / all that's really left to do is make sure we correctly interpret the raycaster results in such a way that we avoid painting labels that cover those holes (which are in many cases going to contain other geographies, with their own labels)

![roanoke](https://user-images.githubusercontent.com/85241/31380007-f6d8cafe-ada7-11e7-8fd5-bd71ec489d1d.png)
![wise](https://user-images.githubusercontent.com/85241/31380008-f7084bc6-ada7-11e7-9552-cfb6c575d7e0.png)
